sudo: required
services:
  - docker

before_install:
  - docker build -t dzenoworldwidewest/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dzenoworldwidewest/react-test npm test -- --coverage

after_success:
  - docker build -t dzenoworldwidewest/multi-client -f ./client
  - docker build -t dzenoworldwidewest/multi-nginx -f ./nginx
  - docker build -t dzenoworldwidewest/multi-server -f ./server
  - docker build -t dzenoworldwidewest/multi-worker -f ./worker
