version: '3'
services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
    restart: always
    depends_on:
      - api
      - client

  postgres:
    image: 'postgres:latest'
    env_file: docker.env
    
  redis:
    image: 'redis:latest'
    env_file: docker.env

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file: docker.env
    depends_on: 
      - postgres
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    env_file: docker.env
    depends_on:
      - api 

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    env_file: docker.env
    depends_on:
      - redis
    